CREATE TABLE [dbo.RestaurantMenu (
  MenuID varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  RestaurantID varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  DisplayOrder smallint NOT NULL,
  FoodCategoryID varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  FoodName varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  FoodDescription varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  OriginalPrice numeric(12,2) NOT NULL,
  SpecialPrice numeric(12,2) NOT NULL,
  NotAvailable bit NOT NULL,
  FoodImage varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  SupplierItemCode varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
  ExtraItem varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  Visible bit NULL,
  RemovedOn datetime NULL,
  PrepTimeMinutes smallint NOT NULL,
  MaximumItemsPerOrder smallint NOT NULL,
  isFeatured bit DEFAULT 0 NOT NULL,
  FeaturedImage varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
  RedeemRank int DEFAULT NULL NULL,
  JavaMenuID varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  Country nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'KENYA' NULL,
  CategoryTag varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CONSTRAINT PK_MenuItems PRIMARY KEY (MenuID,RestaurantID)
